// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0nsu6gntqX6VIMd6xy3hoa78TtRe-8eg',
    appId: '1:891423271636:web:ff97ec2560491e8de2a941',
    messagingSenderId: '891423271636',
    projectId: 'glove-chat',
    authDomain: 'glove-chat.firebaseapp.com',
    storageBucket: 'glove-chat.appspot.com',
    measurementId: 'G-X6YYBJV7VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqc3rZ89wyvXnus3xLTFPb7jdt6vMjqOk',
    appId: '1:891423271636:android:7c7cc3b039ca0df6e2a941',
    messagingSenderId: '891423271636',
    projectId: 'glove-chat',
    storageBucket: 'glove-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbqyXU_v9BuDnVz2bhgTpwoY6gDFrDVY',
    appId: '1:891423271636:ios:70a8a7f21b6f751ae2a941',
    messagingSenderId: '891423271636',
    projectId: 'glove-chat',
    storageBucket: 'glove-chat.appspot.com',
    iosBundleId: 'com.example.gloveChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGbqyXU_v9BuDnVz2bhgTpwoY6gDFrDVY',
    appId: '1:891423271636:ios:0537a802b33fb632e2a941',
    messagingSenderId: '891423271636',
    projectId: 'glove-chat',
    storageBucket: 'glove-chat.appspot.com',
    iosBundleId: 'com.example.gloveChat.RunnerTests',
  );
}
